# Generated by Django 5.0.6 on 2024-06-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aunak_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="uploaded_at",
        ),
        migrations.AddField(
            model_name="video",
            name="grade",
            field=models.CharField(
                choices=[("9", "9th Grade"), ("12", "12th Grade")],
                default="9",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="subject",
            field=models.CharField(
                choices=[("physics", "Physics"), ("math", "Math")],
                default="physics",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
