# Generated by Django 5.0.6 on 2024-06-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aunak_app", "0003_video_uploaded_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="subject_type",
            field=models.CharField(
                choices=[("1", "mukathefat"), ("2", "t2ses"), ("3", "jalsat_e")],
                default="physics",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="subject",
            field=models.CharField(
                choices=[("1", "mukathefat"), ("2", "t2ses"), ("3", "jalsat_e")],
                default="physics",
                max_length=7,
            ),
        ),
    ]
