# Generated by Django 5.0.6 on 2024-07-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aunak_app", "0005_alter_video_subject_videoview"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="teacher",
            field=models.CharField(default="Default Teacher Name", max_length=255),
        ),
    ]
