# Generated by Django 5.0.6 on 2024-07-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aunak_app", "0007_teacher_alter_video_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="teacher",
            field=models.CharField(default="Default Teacher Name", max_length=255),
        ),
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
