# Generated by Django 5.0.6 on 2024-07-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aunak_app", "0010_course_video_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="course",
        ),
        migrations.AlterField(
            model_name="video",
            name="subject_type",
            field=models.CharField(
                choices=[("1", "mukathefat"), ("2", "t2ses"), ("3", "jalsat_e")],
                default="1",
                max_length=7,
            ),
        ),
        migrations.DeleteModel(
            name="Course",
        ),
    ]
