# Generated by Django 5.0.6 on 2024-07-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aunak_app", "0012_course_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="require_videos_at_creation",
            field=models.BooleanField(default=False),
        ),
    ]
