# Generated by Django 5.0.6 on 2024-07-18 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aunak_app", "0013_course_require_videos_at_creation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="require_videos_at_creation",
        ),
    ]
