# Generated by Django 5.0.6 on 2024-07-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aunak_app", "0014_remove_course_require_videos_at_creation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="grade",
            field=models.CharField(
                choices=[
                    ("9", "9th Grade"),
                    ("12", "12th Grade 3lme"),
                    ("13", "12th Grade adabe"),
                ],
                default="9",
                max_length=2,
            ),
        ),
    ]
