# Generated by Django 5.0.6 on 2024-07-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aunak_app", "0017_alter_grade_level_alter_subject_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
