# Generated by Django 5.0.6 on 2024-07-22 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aunak_app", "0018_alter_subject_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject_type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="grade",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="aunak_app.grade",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="aunak_app.subject",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="aunak_app.teacher",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="subject_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="aunak_app.subject_type",
            ),
            preserve_default=False,
        ),
    ]
