# Generated by Django 5.0.6 on 2024-07-22 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aunak_app", "0020_subject_type_grade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject_type",
            name="grade",
        ),
        migrations.AddField(
            model_name="subject",
            name="grade",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="aunak_app.grade",
            ),
            preserve_default=False,
        ),
    ]
