# Generated by Django 5.0.6 on 2024-07-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aunak_app", "0021_remove_subject_type_grade_subject_grade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="video_file",
        ),
        migrations.AddField(
            model_name="video",
            name="video_file_path",
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
    ]
