# Generated by Django 5.0.6 on 2024-07-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aunak_app", "0023_dropboxtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="preview_link",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
