# Generated by Django 5.0.6 on 2024-08-01 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aunak_app", "0024_video_preview_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="aunak_app.subject"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="subject_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="aunak_app.subject_type"
            ),
        ),
    ]
