# Generated by Django 5.0.6 on 2024-08-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aunak_app", "0025_alter_video_subject_alter_video_subject_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="email",
            field=models.CharField(default=21, max_length=255),
            preserve_default=False,
        ),
    ]
