# Generated by Django 5.0.6 on 2024-08-03 07:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aunak_app", "0026_teacher_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="age",
        ),
    ]
