# Generated by Django 5.0.6 on 2024-08-03 08:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aunak_app", "0029_userprofile_email_alter_userprofile_phone_number"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
