# Generated by Django 5.0.6 on 2024-08-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aunak_app", "0033_alter_videoview_user_alter_purchase_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
