# Generated by Django 5.0.6 on 2024-08-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aunak_app", "0037_remove_course_videos_course_videos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="videos",
        ),
        migrations.AddField(
            model_name="course",
            name="videos",
            field=models.ManyToManyField(to="aunak_app.video"),
        ),
    ]
